#!/bin/bash

#############################################
# Template Functions (deploy.sh)
#############################################

# Create deployment script
create_deploy_script() {
    local username=$1
    local repository=$2
    local branch=$3
    local home_dir="/home/$username"
    local deploy_script="$home_dir/deploy.sh"
    
    cat > "$deploy_script" <<'DEPLOYEOF'
#!/bin/bash

#############################################
# Deployment Script
# Auto-generated by Cipi
#############################################

REPO_DIR="$HOME/wwwroot"
LOG_FILE="$HOME/logs/deploy.log"

# Track if any step fails
DEPLOY_FAILED=0

# Helper to run commands and show status
run_step() {
    local description="$1"
    shift
    echo "→ $description"
    if ! "$@" 2>&1; then
        echo "  ✗ Failed: $description"
        echo "  Command: $*"
        DEPLOY_FAILED=1
        return 1
    fi
    return 0
}

echo "─────────────────────────────────────"
echo "Deployment started at $(date)"
echo "─────────────────────────────────────"

# Set umask for secure permissions (750 dirs, 640 files)
umask 027

# Navigate to project directory
cd "$REPO_DIR" || { echo "✗ Failed to cd to $REPO_DIR"; exit 1; }

# Git pull
run_step "Pulling latest changes from Git..." git pull origin BRANCH_PLACEHOLDER || true

# Check if Laravel project
if [ -f "artisan" ]; then
    echo "→ Laravel project detected"
    
    # Create .env file if it doesn't exist
    if [ ! -f ".env" ]; then
        if [ -f ".env.example" ]; then
            run_step "Creating .env from .env.example..." cp .env.example .env || true
        else
            run_step "Creating empty .env file..." touch .env || true
        fi
    fi
    
    # Generate application key if not set
    if ! grep -q "^APP_KEY=" .env 2>/dev/null || grep -q "^APP_KEY=$" .env 2>/dev/null; then
        run_step "Generating application key..." php artisan key:generate || true
    fi
    
    # Composer install
    run_step "Installing Composer dependencies..." composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev || true
    
    # Run migrations
    run_step "Running database migrations..." php artisan migrate --force || true
    
    # Clear cache
    echo "→ Clearing cache..."
    php artisan cache:clear 2>&1 || true
    php artisan config:clear 2>&1 || true
    php artisan view:clear 2>&1 || true
    php artisan route:clear 2>&1 || true
    
    # Optimize
    echo "→ Optimizing application..."
    php artisan config:cache 2>&1 || true
    php artisan route:cache 2>&1 || true
    php artisan view:cache 2>&1 || true
    
    # Run npm if needed
    if [ -f "package.json" ]; then
        run_step "Installing NPM dependencies..." npm ci || true
        
        if grep -q "build" package.json; then
            run_step "Building assets..." npm run build || true
        fi
    fi
    
    # Restart queue workers
    run_step "Restarting queue workers..." php artisan queue:restart || true
fi

# Fix permissions on Laravel storage/cache (need to be writable)
if [ -d "$REPO_DIR/storage" ]; then
    chmod -R 775 "$REPO_DIR/storage" 2>/dev/null || true
fi

if [ -d "$REPO_DIR/bootstrap/cache" ]; then
    chmod -R 775 "$REPO_DIR/bootstrap/cache" 2>/dev/null || true
fi

echo "─────────────────────────────────────"
if [ $DEPLOY_FAILED -eq 1 ]; then
    echo "Deployment completed with errors at $(date)"
    echo "─────────────────────────────────────"
    exit 1
else
    echo "Deployment completed at $(date)"
    echo "─────────────────────────────────────"
fi
DEPLOYEOF
    
    # Replace branch placeholder
    sed -i "s/BRANCH_PLACEHOLDER/$branch/g" "$deploy_script"
    
    # Set ownership and permissions
    chown "$username:$username" "$deploy_script"
    chmod 755 "$deploy_script"
}
