#!/bin/bash

#############################################
# Template Functions (deploy.sh)
#############################################

# Create deployment script
create_deploy_script() {
    local username=$1
    local repository=$2
    local branch=$3
    local home_dir="/home/$username"
    local deploy_script="$home_dir/deploy.sh"
    
    cat > "$deploy_script" <<'DEPLOYEOF'
#!/bin/bash

#############################################
# Deployment Script
# Auto-generated by Cipi
#############################################

set -e

REPO_DIR="$HOME/wwwroot"
LOG_FILE="$HOME/logs/deploy.log"

# Log output to file while still showing on screen
exec > >(tee -a "$LOG_FILE") 2>&1

echo "─────────────────────────────────────"
echo "Deployment started at $(date)"
echo "─────────────────────────────────────"

# Set umask for secure permissions (750 dirs, 640 files)
# This ensures new files created by git/composer/npm have correct permissions
umask 027

# Navigate to project directory
cd "$REPO_DIR"

# Git pull
echo "→ Pulling latest changes from Git..."
git pull origin BRANCH_PLACEHOLDER

# Check if Laravel project
if [ -f "artisan" ]; then
    echo "→ Laravel project detected"
    
    # Create .env file if it doesn't exist
    if [ ! -f ".env" ]; then
        if [ -f ".env.example" ]; then
            echo "→ Creating .env from .env.example..."
            cp .env.example .env
        else
            echo "→ Creating empty .env file..."
            touch .env
        fi
    fi
    
    # Generate application key if not set
    if ! grep -q "^APP_KEY=" .env 2>/dev/null || grep -q "^APP_KEY=$" .env 2>/dev/null; then
        echo "→ Generating application key..."
        php artisan key:generate
    fi
    
    # Composer install
    echo "→ Installing Composer dependencies..."
    composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
    
    # Run migrations
    echo "→ Running database migrations..."
    php artisan migrate --force
    
    # Clear cache
    echo "→ Clearing cache..."
    php artisan cache:clear
    php artisan config:clear
    php artisan view:clear
    php artisan route:clear
    
    # Optimize
    echo "→ Optimizing application..."
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    
    # Run npm if needed
    if [ -f "package.json" ]; then
        echo "→ Installing NPM dependencies..."
        npm ci
        
        if grep -q "build" package.json; then
            echo "→ Building assets..."
            npm run build
        fi
    fi
    
    # Restart queue workers
    echo "→ Restarting queue workers..."
    php artisan queue:restart
fi

# Fix permissions on Laravel storage/cache (need to be writable)
if [ -d "$REPO_DIR/storage" ]; then
    chmod -R 775 "$REPO_DIR/storage"
fi

if [ -d "$REPO_DIR/bootstrap/cache" ]; then
    chmod -R 775 "$REPO_DIR/bootstrap/cache"
fi

echo "─────────────────────────────────────"
echo "Deployment completed at $(date)"
echo "─────────────────────────────────────"
DEPLOYEOF
    
    # Replace branch placeholder
    sed -i "s/BRANCH_PLACEHOLDER/$branch/g" "$deploy_script"
    
    # Set ownership and permissions
    chown "$username:$username" "$deploy_script"
    chmod 755 "$deploy_script"
}
